use crate::crypto::falcon::Falcon;
use crate::crypto::traits::PqcSignature;
use crate::error::{Error, Result};
use alloc::vec::Vec;
use alloc::{format, vec};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Represents a Remote Attestation Quote.
/// In a real system, this would be generated by a TPM 2.0 or secure enclave.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct AttestationQuote {
    /// SHA-256 Hash of PCRs [0..7] (Firmware State)
    pub pcr_digest: Vec<u8>,

    /// Nonce provided by the challenger to prevent replay
    pub nonce: Vec<u8>,

    /// Signature of the stored data by the Attestation Key (AK)
    /// Algorithm: Falcon-512 or ECDSA-P256 (Hybrid)
    pub signature: Vec<u8>,

    /// The public key verification data or certificate chain for AK
    pub ak_public_key: Vec<u8>,
}

impl AttestationQuote {
    /// Create a new initial measurement (e.g. at boot).
    pub fn new_initial_measurement(nonce: Vec<u8>) -> Self {
        Self {
            pcr_digest: vec![0u8; 32],
            nonce,
            signature: vec![],
            ak_public_key: vec![],
        }
    }

    /// Verify the quote against an expected nonce and PCR digest.
    pub fn verify(&self, expected_nonce: &[u8], expected_pcr_digest: &[u8]) -> Result<()> {
        // 1. Verify Nonce
        if self.nonce != expected_nonce {
            return Err(Error::CryptoError("Quote Nonce Mismatch".into()));
        }

        // 2. Verify PCR Digest
        if self.pcr_digest != expected_pcr_digest {
            return Err(Error::CryptoError(
                "Quote PCR state Mismatch (Tampered Firmware)".into(),
            ));
        }

        // 3. Verify Signature using AK
        let falcon = Falcon::new();
        let mut hasher = Sha256::new();
        hasher.update(&self.pcr_digest);
        hasher.update(&self.nonce);
        let digest = hasher.finalize();

        if !falcon
            .verify(&self.ak_public_key, &digest, &self.signature)
            .map_err(|e| Error::CryptoError(format!("Quote Signature Invalid: {:?}", e)))?
        {
            return Err(Error::CryptoError(
                "Quote Signature Verification Failed (Logic)".into(),
            ));
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quote_verify_accepts_valid_signature() {
        let falcon = Falcon::new();
        let (pk, sk) = falcon.generate_keypair().expect("falcon keygen");

        let pcr_digest = vec![7u8; 32];
        let nonce = vec![1u8, 2, 3, 4];

        let mut hasher = Sha256::new();
        hasher.update(&pcr_digest);
        hasher.update(&nonce);
        let digest = hasher.finalize();
        let signature = falcon.sign(&sk, &digest).expect("falcon sign");

        let quote = AttestationQuote {
            pcr_digest: pcr_digest.clone(),
            nonce: nonce.clone(),
            signature,
            ak_public_key: pk,
        };

        quote
            .verify(&nonce, &pcr_digest)
            .expect("quote should verify");
    }

    #[test]
    fn quote_verify_rejects_tampered_signature() {
        let falcon = Falcon::new();
        let (pk, sk) = falcon.generate_keypair().expect("falcon keygen");

        let pcr_digest = vec![9u8; 32];
        let nonce = vec![4u8, 3, 2, 1];

        let mut hasher = Sha256::new();
        hasher.update(&pcr_digest);
        hasher.update(&nonce);
        let digest = hasher.finalize();
        let mut signature = falcon.sign(&sk, &digest).expect("falcon sign");
        signature[0] ^= 0x01;

        let quote = AttestationQuote {
            pcr_digest: pcr_digest.clone(),
            nonce: nonce.clone(),
            signature,
            ak_public_key: pk,
        };

        assert!(quote.verify(&nonce, &pcr_digest).is_err());
    }
}
