use serde::{Serialize, Deserialize};
use crate::error::{Error, Result};
use crate::crypto::falcon::Falcon;
use crate::crypto::traits::PqcSignature;
use sha2::{Sha256, Digest};

/// Represents a Remote Attestation Quote.
/// In a real system, this would be generated by a TPM 2.0 or secure enclave.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct AttestationQuote {
    /// SHA-256 Hash of PCRs [0..7] (Firmware State)
    pub pcr_digest: Vec<u8>,
    
    /// Nonce provided by the challenger to prevent replay
    pub nonce: Vec<u8>,
    
    /// Signature of the stored data by the Attestation Key (AK)
    /// Algorithm: Falcon-512 or ECDSA-P256 (Hybrid)
    pub signature: Vec<u8>,
    
    /// The public key verification data or certificate chain for AK
    pub ak_public_key: Vec<u8>,
}

impl AttestationQuote {
    /// Create a new initial measurement (e.g. at boot).
    pub fn new_initial_measurement(nonce: Vec<u8>) -> Self {
        Self {
            pcr_digest: vec![0u8; 32],
            nonce,
            signature: vec![],
            ak_public_key: vec![],
        }
    }

    /// Verify the quote against an expected nonce and PCR digest.
    pub fn verify(&self, expected_nonce: &[u8], expected_pcr_digest: &[u8]) -> Result<()> {
        // 1. Verify Nonce
        if self.nonce != expected_nonce {
            return Err(Error::CryptoError("Quote Nonce Mismatch".into()));
        }
        
        // 2. Verify PCR Digest
        if self.pcr_digest != expected_pcr_digest {
            return Err(Error::CryptoError("Quote PCR state Mismatch (Tampered Firmware)".into()));
        }
        
        // 3. Verify Signature using AK
        let falcon = Falcon::new();
        let mut hasher = Sha256::new();
        hasher.update(&self.pcr_digest);
        hasher.update(&self.nonce);
        let digest = hasher.finalize();
        
        if !falcon.verify(&self.signature, &digest, &self.ak_public_key)
            .map_err(|e| Error::CryptoError(format!("Quote Signature Invalid: {:?}", e)))? 
        {
            return Err(Error::CryptoError("Quote Signature Verification Failed (Logic)".into()));
        }
        Ok(())
    }
}
