use serde::{Serialize, Deserialize};
// Access to crypto traits for key management. Using Vec<u8> as the standardized storage format.

/// Industrial Provisioning Protocol
/// 
/// Implements the "Factory Born" -> "Operational" lifecycle transition.
/// 
/// Flow:
/// 1. Device boots with strict "Factory Identity" (Immutable, fused).
/// 2. Device generates a "Join Request" signing its new "Operational Key" with Factory Key.
/// 3. Gateway verifies Factory Sig against Allow-list.
/// 4. Gateway issues "Operational Certificate".

#[derive(Debug, Serialize, Deserialize)]
pub struct JoinRequest {
    /// The immutable Factory Public Key (Falcon-512)
    /// Acts as the hardware root of trust.
    pub factory_pubkey: Vec<u8>,
    
    /// Unique Device Serial / UUID
    pub device_id: String,
    
    /// The NEW Operational Public Key generated by the device
    /// This key will be used for day-to-day MTLS/MQTT operations.
    pub proposed_operational_pubkey: Vec<u8>,
    
    /// Proof of possession of Factory Key
    /// Sign(Hash(device_id || proposed_operational_pubkey))
    pub factory_signature: Vec<u8>,
    
    /// (Optional) Remote Attestation Quote from Bootloader
    /// Proves firmware integrity to the CA.
    pub attestation_quote: Option<Vec<u8>>,
}

#[derive(Debug, Serialize, Deserialize)]
/// Response from the Gateway/CA to a Join Request.
pub struct JoinResponse {
    /// The issued Operational Certificate
    /// Signed by the Factory CA.
    pub operational_cert: Vec<u8>,
    
    /// Expiration timestamp (Unix)
    pub expires_at: u64,
    
    /// Trust Anchor update (Root CA for the mesh)
    pub root_ca_pubkey: Vec<u8>,
}

/// Represents the Immutable Device Identity (Fused in Hardware).
pub struct FactoryIdentity {
    /// Factory Public Key (Falcon-512).
    pub pubkey: Vec<u8>,
    #[allow(dead_code)] // Will be used in real HW operations
    secret_key: Vec<u8>, // Protected memory
}

impl FactoryIdentity {
    /// Load Factory Identity from secure storage/fuses.
    pub fn new(pk: Vec<u8>, sk: Vec<u8>) -> Self {
        Self { pubkey: pk, secret_key: sk }
    }

    /// Creates a Join Request to onboard into a specific mesh/site.
    pub fn create_join_request(
        &self, 
        device_id: &str, 
        operational_pk: &[u8],
        signer: &dyn crate::security::provider::SecurityProvider
    ) -> crate::error::Result<JoinRequest> {
        // 1. Construct payload to sign
        let mut payload = Vec::new();
        payload.extend_from_slice(device_id.as_bytes());
        payload.extend_from_slice(operational_pk);
        
        // 2. Sign with Factory Key (Falcon-512) using the Provider
        // This ensures secrets are handled inside the secure boundary (TPM/Enclave)
        let signature = signer.sign(&payload)?;
        
        Ok(JoinRequest {
            factory_pubkey: self.pubkey.clone(),
            device_id: device_id.to_string(),
            proposed_operational_pubkey: operational_pk.to_vec(),
            factory_signature: signature,
            attestation_quote: None, // Can be filled by bootloader
        })
    }
}
