use alloc::string::String;
use alloc::vec::Vec;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::crypto::falcon::{Falcon, FalconSecurityLevel};
use crate::crypto::traits::PqcSignature;
use crate::error::{Error, Result};

/// Industrial Provisioning Protocol
///
/// Implements the "Factory Born" -> "Operational" lifecycle transition.
///
/// Flow:
/// 1. Device boots with strict "Factory Identity" (Immutable, fused).
/// 2. Device generates a "Join Request" signing its new "Operational Key" with Factory Key.
/// 3. Gateway verifies Factory Sig against Allow-list.
/// 4. Gateway issues "Operational Certificate".

#[derive(Debug, Serialize, Deserialize)]
pub struct JoinRequest {
    /// The immutable Factory Public Key (Falcon-512)
    /// Acts as the hardware root of trust.
    #[serde(with = "crate::security::keystore::base64_serde")]
    pub factory_pubkey: Vec<u8>,

    /// Unique Device Serial / UUID
    pub device_id: String,

    /// NEW Operational Kyber KEM public key generated by the device.
    #[serde(with = "crate::security::keystore::base64_serde")]
    pub proposed_kem_pk: Vec<u8>,

    /// NEW Operational Falcon signature public key generated by the device.
    #[serde(with = "crate::security::keystore::base64_serde")]
    pub proposed_sig_pk: Vec<u8>,

    /// NEW Operational X25519 static public key generated by the device.
    /// This binds the classical side of the Hybrid KEM to the certified identity.
    #[serde(with = "crate::security::keystore::base64_serde")]
    pub proposed_x25519_pk: Vec<u8>,

    /// Proof of possession of Factory Key
    /// Sign(JoinRequestPayloadV1(device_id, proposed_*))
    #[serde(with = "crate::security::keystore::base64_serde")]
    pub factory_signature: Vec<u8>,

    /// (Optional) Remote Attestation Quote from Bootloader
    /// Proves firmware integrity to the CA.
    pub attestation_quote: Option<crate::attestation::quote::AttestationQuote>,
}

#[derive(Debug, Serialize, Deserialize)]
/// Response from the Gateway/CA to a Join Request.
pub struct JoinResponse {
    /// The issued Operational Certificate
    /// Signed by the Factory CA.
    pub operational_cert: OperationalCertificate,

    /// Trust Anchor update (Root CA for the mesh)
    pub root_ca_pubkey: Vec<u8>,
}

/// Minimal operational certificate for the IIoT mesh.
///
/// This is intentionally simple and deterministic. It is *not* X.509.
/// The verification rule is:
/// - verify `signature` with the pinned CA public key
/// - enforce `device_id` binding and time window
/// - enforce `key_id` consistency with (device_id, key_epoch, keys)
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct OperationalCertificate {
    /// Schema version for forward compatibility.
    pub version: u8,

    /// Identity binding (must match the MQTT topic suffix / peer_id).
    pub device_id: String,

    /// Monotonic epoch for anti-rollback and clean rotations.
    pub key_epoch: u64,

    /// 128-bit identifier derived from the certified key material and epoch.
    #[serde(with = "crate::security::keystore::base64_serde")]
    pub key_id: Vec<u8>,

    /// Validity window (unix seconds).
    pub not_before: u64,
    /// Certificate expiration timestamp (unix seconds).
    pub expires_at: u64,

    /// Certified public keys.
    #[serde(with = "crate::security::keystore::base64_serde")]
    pub kem_pk: Vec<u8>,
    /// Falcon public key bound to this device identity (used to verify signed announcements).
    #[serde(with = "crate::security::keystore::base64_serde")]
    pub sig_pk: Vec<u8>,
    /// X25519 static public key bound to this device identity (hybrid KEM classical side).
    #[serde(with = "crate::security::keystore::base64_serde")]
    pub x25519_pk: Vec<u8>,

    /// Detached Falcon signature by the CA over `cert_payload_v1`.
    #[serde(with = "crate::security::keystore::base64_serde")]
    pub signature: Vec<u8>,
}

impl OperationalCertificate {
    /// Current operational certificate schema version.
    pub const VERSION_V1: u8 = 1;

    /// Compute a stable `key_id` for a given certified key set and epoch.
    ///
    /// `key_id` is an operational identifier (not a secret). It exists to:
    /// - bind rotations to a monotonic `key_epoch`
    /// - support local revocation lists
    /// - detect epoch collisions (same epoch, different key material)
    pub fn key_id_v1(
        device_id: &str,
        key_epoch: u64,
        kem_pk: &[u8],
        sig_pk: &[u8],
        x25519_pk: &[u8],
    ) -> [u8; 16] {
        let mut hasher = Sha256::new();
        hasher.update(b"pqc-iiot:key-id:v1");
        hasher.update((device_id.len() as u16).to_be_bytes());
        hasher.update(device_id.as_bytes());
        hasher.update(key_epoch.to_be_bytes());
        hasher.update((kem_pk.len() as u32).to_be_bytes());
        hasher.update(kem_pk);
        hasher.update((sig_pk.len() as u32).to_be_bytes());
        hasher.update(sig_pk);
        hasher.update((x25519_pk.len() as u32).to_be_bytes());
        hasher.update(x25519_pk);
        let digest = hasher.finalize();
        let mut out = [0u8; 16];
        out.copy_from_slice(&digest[..16]);
        out
    }

    fn cert_payload_v1(&self) -> Vec<u8> {
        let mut buf = Vec::new();
        buf.extend_from_slice(b"pqc-iiot:op-cert:v1");
        buf.push(self.version);
        buf.extend_from_slice(&(self.device_id.len() as u16).to_be_bytes());
        buf.extend_from_slice(self.device_id.as_bytes());
        buf.extend_from_slice(&self.key_epoch.to_be_bytes());
        buf.extend_from_slice(&self.not_before.to_be_bytes());
        buf.extend_from_slice(&self.expires_at.to_be_bytes());
        buf.extend_from_slice(&(self.key_id.len() as u16).to_be_bytes());
        buf.extend_from_slice(&self.key_id);
        buf.extend_from_slice(&(self.kem_pk.len() as u32).to_be_bytes());
        buf.extend_from_slice(&self.kem_pk);
        buf.extend_from_slice(&(self.sig_pk.len() as u32).to_be_bytes());
        buf.extend_from_slice(&self.sig_pk);
        buf.extend_from_slice(&(self.x25519_pk.len() as u32).to_be_bytes());
        buf.extend_from_slice(&self.x25519_pk);
        buf
    }

    /// Verify certificate integrity and consistency.
    ///
    /// If `now` is provided, validity window is enforced. If `None`, only signature and key_id are checked.
    pub fn verify(&self, ca_sig_pk: &[u8], now: Option<u64>) -> Result<()> {
        if self.version != Self::VERSION_V1 {
            return Err(Error::ProtocolError(format!(
                "Unsupported operational cert version: {}",
                self.version
            )));
        }

        if self.x25519_pk.len() != 32 {
            return Err(Error::InvalidInput(format!(
                "Invalid x25519_pk length in cert: {}",
                self.x25519_pk.len()
            )));
        }

        if let Some(ts) = now {
            if ts < self.not_before || ts > self.expires_at {
                return Err(Error::ProtocolError(
                    "Operational cert expired/not yet valid".into(),
                ));
            }
        }

        // key_id consistency check
        let expected_key_id = Self::key_id_v1(
            &self.device_id,
            self.key_epoch,
            &self.kem_pk,
            &self.sig_pk,
            &self.x25519_pk,
        );
        if self.key_id.len() != expected_key_id.len() || self.key_id.as_slice() != expected_key_id {
            return Err(Error::ProtocolError(
                "Operational cert key_id mismatch".into(),
            ));
        }

        let payload = self.cert_payload_v1();
        let ok = falcon_verify_auto(ca_sig_pk, &payload, &self.signature)?;
        if !ok {
            return Err(Error::SignatureVerification(
                "Operational cert signature invalid".into(),
            ));
        }
        Ok(())
    }
}

/// Represents the Immutable Device Identity (Fused in Hardware).
pub struct FactoryIdentity {
    /// Factory Public Key (Falcon-512).
    pub pubkey: Vec<u8>,
    #[allow(dead_code)] // Will be used in real HW operations
    secret_key: Vec<u8>, // Protected memory
}

impl FactoryIdentity {
    /// Load Factory Identity from secure storage/fuses.
    pub fn new(pk: Vec<u8>, sk: Vec<u8>) -> Self {
        Self {
            pubkey: pk,
            secret_key: sk,
        }
    }

    /// Creates a Join Request to onboard into a specific mesh/site.
    pub fn create_join_request(
        &self,
        device_id: &str,
        operational_kem_pk: &[u8],
        operational_sig_pk: &[u8],
        operational_x25519_pk: &[u8],
    ) -> Result<JoinRequest> {
        if operational_x25519_pk.len() != 32 {
            return Err(Error::InvalidInput(format!(
                "Invalid proposed_x25519_pk length: {}",
                operational_x25519_pk.len()
            )));
        }

        let payload = join_request_payload_v1(
            device_id,
            operational_kem_pk,
            operational_sig_pk,
            operational_x25519_pk,
        );

        // Sign with Factory Key (immutable).
        let signature = falcon_sign_auto(&self.secret_key, &payload)?;

        Ok(JoinRequest {
            factory_pubkey: self.pubkey.clone(),
            device_id: device_id.to_string(),
            proposed_kem_pk: operational_kem_pk.to_vec(),
            proposed_sig_pk: operational_sig_pk.to_vec(),
            proposed_x25519_pk: operational_x25519_pk.to_vec(),
            factory_signature: signature,
            attestation_quote: None, // Filled by bootloader / verifier policy
        })
    }
}

fn join_request_payload_v1(
    device_id: &str,
    proposed_kem_pk: &[u8],
    proposed_sig_pk: &[u8],
    proposed_x25519_pk: &[u8],
) -> Vec<u8> {
    let mut buf = Vec::new();
    buf.extend_from_slice(b"pqc-iiot:join-request:v1");
    buf.extend_from_slice(&(device_id.len() as u16).to_be_bytes());
    buf.extend_from_slice(device_id.as_bytes());
    buf.extend_from_slice(&(proposed_kem_pk.len() as u32).to_be_bytes());
    buf.extend_from_slice(proposed_kem_pk);
    buf.extend_from_slice(&(proposed_sig_pk.len() as u32).to_be_bytes());
    buf.extend_from_slice(proposed_sig_pk);
    buf.extend_from_slice(&(proposed_x25519_pk.len() as u32).to_be_bytes());
    buf.extend_from_slice(proposed_x25519_pk);
    buf
}

fn falcon_verify_auto(pk: &[u8], msg: &[u8], sig: &[u8]) -> Result<bool> {
    let level = match pk.len() {
        897 => FalconSecurityLevel::Falcon512,
        1793 => FalconSecurityLevel::Falcon1024,
        _ => {
            return Err(Error::InvalidInput(format!(
                "Invalid Falcon public key length: {}",
                pk.len()
            )))
        }
    };
    let falcon = Falcon::new_with_level(level);
    falcon.verify(pk, msg, sig)
}

fn falcon_sign_auto(sk: &[u8], msg: &[u8]) -> Result<Vec<u8>> {
    let level = match sk.len() {
        1281 => FalconSecurityLevel::Falcon512,
        2305 => FalconSecurityLevel::Falcon1024,
        _ => {
            return Err(Error::InvalidInput(format!(
                "Invalid Falcon secret key length: {}",
                sk.len()
            )))
        }
    };
    let falcon = Falcon::new_with_level(level);
    falcon.sign(sk, msg)
}

#[cfg(feature = "std")]
/// Minimal in-memory provisioning CA.
///
/// This is intentionally *not* a PKI implementation. It enforces a very narrow
/// security model:
/// - devices prove possession of a factory key (allowlisted by `device_id`)
/// - the CA issues an `OperationalCertificate` binding `(device_id, epoch, keys)`
/// - the CA enforces monotonic epochs per device to prevent rollback
pub struct OperationalCa {
    ca_pubkey: Vec<u8>,
    ca_secret_key: Vec<u8>,
    allowlist: std::collections::HashMap<String, Vec<u8>>,
    next_epoch: std::collections::HashMap<String, u64>,
}

#[cfg(feature = "std")]
impl OperationalCa {
    /// Create a new in-memory CA for provisioning.
    pub fn new(ca_pubkey: Vec<u8>, ca_secret_key: Vec<u8>) -> Self {
        Self {
            ca_pubkey,
            ca_secret_key,
            allowlist: std::collections::HashMap::new(),
            next_epoch: std::collections::HashMap::new(),
        }
    }

    /// Return the CA public key used by peers to verify issued certificates.
    pub fn ca_pubkey(&self) -> &[u8] {
        &self.ca_pubkey
    }

    /// Add a device entry to the factory allowlist.
    ///
    /// Operational certificates are only issued if the join request proves
    /// possession of the factory key and matches this allowlist binding.
    pub fn allow_device(&mut self, device_id: &str, factory_pubkey: Vec<u8>) {
        self.allowlist.insert(device_id.to_string(), factory_pubkey);
    }

    /// Verify a join request against the factory allowlist and the factory signature.
    pub fn verify_join_request(&self, jr: &JoinRequest) -> Result<()> {
        let expected_factory_pk = self.allowlist.get(&jr.device_id).ok_or_else(|| {
            Error::ProtocolError(format!(
                "Device '{}' not present in factory allowlist",
                jr.device_id
            ))
        })?;

        if expected_factory_pk.as_slice() != jr.factory_pubkey.as_slice() {
            return Err(Error::ProtocolError(
                "Factory pubkey mismatch for device_id allowlist entry".into(),
            ));
        }

        if jr.proposed_x25519_pk.len() != 32 {
            return Err(Error::InvalidInput(format!(
                "Invalid proposed_x25519_pk length: {}",
                jr.proposed_x25519_pk.len()
            )));
        }

        let payload = join_request_payload_v1(
            &jr.device_id,
            &jr.proposed_kem_pk,
            &jr.proposed_sig_pk,
            &jr.proposed_x25519_pk,
        );

        let ok = falcon_verify_auto(&jr.factory_pubkey, &payload, &jr.factory_signature)?;
        if !ok {
            return Err(Error::SignatureVerification(
                "Join request factory signature invalid".into(),
            ));
        }

        // Optional: attestation gating belongs here (policy-driven).
        Ok(())
    }

    /// Issue a new operational certificate for a verified join request.
    ///
    /// The CA enforces monotonic `key_epoch` per device_id to support safe rotations and anti-rollback.
    pub fn issue_operational_cert(
        &mut self,
        jr: &JoinRequest,
        now: u64,
        validity_secs: u64,
    ) -> Result<OperationalCertificate> {
        self.verify_join_request(jr)?;

        let epoch = self
            .next_epoch
            .entry(jr.device_id.clone())
            .and_modify(|e| *e += 1)
            .or_insert(1);

        let key_id = OperationalCertificate::key_id_v1(
            &jr.device_id,
            *epoch,
            &jr.proposed_kem_pk,
            &jr.proposed_sig_pk,
            &jr.proposed_x25519_pk,
        );

        let mut cert = OperationalCertificate {
            version: OperationalCertificate::VERSION_V1,
            device_id: jr.device_id.clone(),
            key_epoch: *epoch,
            key_id: key_id.to_vec(),
            not_before: now,
            expires_at: now.saturating_add(validity_secs),
            kem_pk: jr.proposed_kem_pk.clone(),
            sig_pk: jr.proposed_sig_pk.clone(),
            x25519_pk: jr.proposed_x25519_pk.clone(),
            signature: Vec::new(),
        };

        let payload = cert.cert_payload_v1();
        let sig = falcon_sign_auto(&self.ca_secret_key, &payload)?;
        cert.signature = sig;
        Ok(cert)
    }

    /// Process a join request end-to-end, returning an operational certificate + CA pubkey.
    pub fn process_join_request(
        &mut self,
        jr: &JoinRequest,
        now: u64,
        validity_secs: u64,
    ) -> Result<JoinResponse> {
        let cert = self.issue_operational_cert(jr, now, validity_secs)?;
        Ok(JoinResponse {
            operational_cert: cert,
            root_ca_pubkey: self.ca_pubkey.clone(),
        })
    }
}
